---
# Integration Test Scenario (ITS) custom resource consumed by Konflux.
# It tells Konflux which Tekton Pipeline to run for integration tests and
# passes parameters that the pipeline/task will use to talk to Testing Farm.

apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  # Choose a stable, DNS-safe name for the scenario
  name: testing-farm-integration
  # Namespace (tenant workspace) where your app and tests live
  namespace: <your-tenant-namespace>
  labels:
    # If "true", the ITS is optional and won't block promotions.
    # Keep "false" to make failures block delivery.
    test.appstudio.openshift.io/optional: "false"
spec:
  # Exact Konflux Application name this scenario belongs to
  application: <your-konflux-application>

  # Reference the Tekton Pipeline via the Git resolver. Konflux fetches it
  # from your repository at the specified path/revision.
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/<org>/<repo-tests>.git
      - name: revision
        value: main
      - name: pathInRepo
        # Path to the pipeline YAML in your repo
        value: tekton/pipelines/testing-farm-pipeline.yaml

  # Parameters forwarded to the Pipeline (and then to the Task).
  # Adjust these to your needs or override per-scenario.
  params:
    # Testing Farm target environment
    - name: TF_COMPOSE
      value: Fedora-41
    - name: TF_ARCH
      value: x86_64

    # Repository containing your FMF/tmt metadata and tests
    - name: TF_GIT_URL
      value: https://github.com/<org>/<repo-tests>.git
    - name: TF_GIT_REF
      value: main

    # Path to the tmt plan in your repo (defined below)
    - name: TF_PLAN
      value: /plans/run-root-script

    # End-to-end timeout for the Testing Farm request, in minutes
    - name: TF_TIMEOUT_MIN
      value: "120"

    # Extra environment variables passed to the tmt plan.
    # Defaults below assume your script lives at ./tests/script.sh
    # and runs with a couple of flags. Extend as needed.
    - name: TF_TMT_ENV
      value: >
        SCRIPT_PATH=./tests/script.sh SCRIPT_ARGS="--flag1 --flag2" USE_CONTAINER=false PACKAGE_LIST="podman jq"
