---
# Minimal Tekton Pipeline that delegates to a single Task which
# submits a request to Testing Farm, then waits and fails/passes accordingly.

apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testing-farm-pipeline
spec:
  description: >
    Submit and monitor a Testing Farm request which executes tmt plans that run our root/privileged script.
  # Pipeline parameters mirror ITS params one-to-one for clarity.
  params:
    - name: TF_COMPOSE
      type: string
      description: Testing Farm compose (e.g. Fedora-41, RHEL-9.4)
    - name: TF_ARCH
      type: string
      default: x86_64
      description: Target architecture
    - name: TF_GIT_URL
      type: string
      description: Git repo URL containing tmt tests/plans
    - name: TF_GIT_REF
      type: string
      default: main
      description: Branch/commit/SHA for tmt tests
    - name: TF_PLAN
      type: string
      description: FMF path to the tmt plan (e.g. /plans/run-root-script)
    - name: TF_TIMEOUT_MIN
      type: string
      default: "120"
      description: End-to-end TF timeout in minutes
    - name: TF_TMT_ENV
      type: string
      default: ""
      description: Space-separated K=V list passed to tmt as environment

  # Single task which contains the Testing Farm CLI calls.
  tasks:
    - name: run-testing-farm
      # Keep the Task versioned in Git as well (good supply-chain practice).
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/<org>/<repo-tests>.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tekton/tasks/testing-farm-request.yaml
      params:
        - name: TF_COMPOSE
          value: $(params.TF_COMPOSE)
        - name: TF_ARCH
          value: $(params.TF_ARCH)
        - name: TF_GIT_URL
          value: $(params.TF_GIT_URL)
        - name: TF_GIT_REF
          value: $(params.TF_GIT_REF)
        - name: TF_PLAN
          value: $(params.TF_PLAN)
        - name: TF_TIMEOUT_MIN
          value: $(params.TF_TIMEOUT_MIN)
        - name: TF_TMT_ENV
          value: $(params.TF_TMT_ENV)

